<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meet.proto

namespace GPBMetadata\Proto;

class Meet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a1070726f746f2f6d6565742e70726f746f120467727063221c0a" .
            "0c48656c6c6f52657175657374120c0a046e616d6518012001280922200a" .
            "0d48656c6c6f526573706f6e7365120f0a076d656574696e671801200128" .
            "09323a0a044d65657412320a0548656c6c6f12122e677270632e48656c6c" .
            "6f526571756573741a132e677270632e48656c6c6f526573706f6e736522" .
            "00620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

